- .github/workflows/ci-cd.yml
#issue
- chromatic 배포 워크플로우에 autoAcceptChanges 옵션 추가
> chromatic 배포시 autoAcceptChanges 옵션 추가

- .storybook/main.js
> 스토리북 절대경로 세팅

- app/calendar/page.tsx
- components/pages/Calendar/Calendar/Calendar.tsx
- libs/message/message.ts
- package.json
- tools/firebase-authentication-simple-client/.gitignore
- tools/firebase-authentication-simple-client/README.md
- tools/firebase-authentication-simple-client/index.js
- tools/firebase-authentication-simple-client/lib/Command.js
- tools/firebase-authentication-simple-client/lib/UserJoinRequestClient.js
- tools/firebase-authentication-simple-client/lib/UserLoginRequestClient.js
- tools/firebase-authentication-simple-client/package-lock.json
- tools/firebase-authentication-simple-client/package.json
- utils/datetime.ts
- yarn.lock
- https://github.com/YAPP-Github/21st-ALL-Rounder-Team-2-Web/issues/35
#issue
- 캘린더 api 연동
> 캘린더 API 연동

- app/exhibition/[exhibitionId]/page.tsx
- components/pages/ArtworkCardList/ArtworkCardList.stories.tsx
- components/pages/ArtworkCardList/ArtworkCardList.tsx
- components/pages/ExhibitionInfoHeader/ExhibitionInfoHeader.stories.tsx
- components/pages/ExhibitionInfoHeader/ExhibitionInfoHeader.tsx
- components/pages/Home/CategoryList/CategoryList.stories.tsx
- components/ui/CustomSuspense/CustomSuspense.tsx
- libs/message/message.ts
> 브릿지 연결 및 suspense 적용

- app/exhibition/[exhibitionId]/[artworkId]/page.styles.tsx
- app/exhibition/[exhibitionId]/[artworkId]/page.tsx
- components/pages/ArtworkCardList/ArtworkCardList.styles.tsx
- components/pages/ArtworkCardList/ArtworkCardList.tsx
- components/ui/ActionSheet/ActionSheet.styles.tsx
- components/ui/Dimmed/Dimmed.tsx
- styles/keyframes.ts
#issue
- slideup, slidedown 애니메이션 추가
- 바텀시트, 액션시트에 적용
> 오버레이 애니메이션 효과 추가

- apis/artwork.ts
#issue
- codegen 컨트롤러의 base path를 undefined로 설정
> base path 오류 수정

- app/exhibition/[exhibitionId]/[artworkId]/page.styles.tsx
- components/pages/ArtworkCardList/ArtworkCardList.styles.tsx
- components/pages/ExhibitionInfoHeader/ExhibitionInfoHeader.styles.tsx
> 네비게이션바 padding-top 추가

- app/exhibition/[exhibitionId]/[artworkId]/page.tsx
- components/pages/ArtworkCardList/ArtworkCardList.tsx
- components/pages/ArtworkDeleteAlertModal/ArtworkDeleteAlertModal.stories.tsx
- components/pages/ArtworkDeleteAlertModal/ArtworkDeleteAlertModal.styles.tsx
- components/pages/ArtworkDeleteAlertModal/ArtworkDeleteAlertModal.tsx
- components/pages/ImageUploadSelectModal/ImageUploadSelectModal.styles.tsx
- components/ui/Modal/Modal.styles.tsx
- components/ui/Modal/Modal.tsx
- styles/colors.ts
#issue
- 경고 모달 띄우기
- 슬라이더 인덱스, 작품 id 싱크 오류 수정
> 마지막 작품 삭제 시도시 경고 모달 띄우기

- app/exhibition/[exhibitionId]/[artworkId]/page.tsx
- app/home/page.styles.tsx
- components/pages/ArtworkCard/ArtworkCard.styles.tsx
- components/pages/ArtworkCard/ArtworkCard.tsx
- components/pages/ExhibitionInfoHeader/ExhibitionInfoHeader.styles.tsx
- components/pages/ExhibitionInfoHeader/ExhibitionInfoHeader.tsx
- components/pages/Home/AppBar/AppBar.styles.tsx
- components/pages/Home/Category/Category.styles.tsx
- components/pages/Home/ExhibitionCard/ExhibitionCard.styles.tsx
- components/pages/Home/ExhibitionCardList/ExhibitionCardList.styles.tsx
- components/pages/Home/MainExhibitionCard/MainExhibitionCard.styles.tsx
- components/pages/Home/MainExhibitionCard/MainExhibitionCard.tsx
- components/ui/Button/IconButton/IconButton.styles.tsx
- components/ui/NavigationBar/NavigationBar.styles.tsx
- components/ui/NavigationBar/NavigationBar.tsx
- components/ui/Select/Select.styles.tsx
- components/ui/Tag/Tag/Tag.styles.tsx
- components/ui/Tag/Tag/Tag.tsx
> 스타일 변경사항 적용

- app/exhibition/[exhibitionId]/[artworkId]/page.styles.tsx
- app/exhibition/[exhibitionId]/[artworkId]/page.tsx
- components/pages/ArtworkCardList/ArtworkCardList.styles.tsx
- components/pages/ArtworkCardList/ArtworkCardList.tsx
- components/pages/ArtworkDeleteAlertModal/ArtworkDeleteAlertModal.tsx
- components/pages/ImageUploadSelectModal/ImageUploadSelectModal.tsx
- components/ui/ActionSheet/ActionSheet.styles.tsx
- components/ui/ActionSheet/ActionSheet.tsx
- components/ui/Animated/Animated.tsx
- components/ui/Modal/Modal.styles.tsx
- components/ui/Modal/Modal.tsx
unmount시 애니메이션을 적용하기 위한 방식 개선
- 기존 방식은 매번 애니메이션 트리거 변수를 선언하고 setTimeout을 통해 애니메이션 이후 unmount 되도록 처리해야 했다.
- 이를 보다 선언적으로 처리할 수 있는 방식 제안
- setTimeout 대신 animation end 이벤트 활용
- 애니메이션 트리거 변수 및 animation end 이벤트 핸들러를 관리하는 Animated 컴포넌트 구현
> animation 적용 방식 개선

- app/exhibition/[exhibitionId]/[artworkId]/page.tsx
- hooks/useOverlay.tsx
- next.config.js
> 바텀시트가 닫히지 않는 버그 수정

- __generate__/post/api.ts
- apis/calendar.ts
- app/calendar/page.tsx
- components/pages/Calendar/Calendar/Calendar.styles.tsx
- components/pages/Calendar/Calendar/Calendar.tsx
- components/pages/Calendar/ExhibitSelectModal/ExhibitSelectModal.stories.tsx
- components/pages/Calendar/ExhibitSelectModal/ExhibitSelectModal.styles.tsx
- components/pages/Calendar/ExhibitSelectModal/ExhibitSelectModal.tsx
- components/pages/Home/CategoryList/CategoryList.stories.tsx
- components/ui/Picker/DatePicker/DatePicker.tsx
- hooks/calendar.tsx
- utils/datetime.ts
#issue
- 전시 기록이 여러 개인 경우 처리
- 전시 기록 개수 표시
- 클릭시 전시 선택 모달 띄우기
- 날짜별 전시 기록 조회
- 날짜 선택시 전시 정보 페이지로 라우팅 처리
- calendar, date picker 선택 가능 날짜 제한
> 캘린더 페이지 추가 구현

- .storybook/preview-head.html
- .storybook/preview.js
- app/calendar/page.stories.tsx
- app/exhibition/[exhibitionId]/[artworkId]/pages.stories.tsx
- app/exhibition/[exhibitionId]/page.stories.tsx
- app/home/page.stories.tsx
> Storybook preview 설정 추가

- .github/workflows/ci-cd.yml
- .storybook/main.js
> 프록시 서버 url 환경 변수 추가

- .github/workflows/ci-cd.yml
- .storybook/main.js
This reverts commit cf7971e65c38b1b11a34b1c4159b1d956c876d37.
#issue
> Revert "chore: 프록시 서버 url 환경 변수 추가 (#61)"

- .storybook/main.js
- apis/exhibition.ts
- mocks/handlers/exhibition.ts
> 환경 변수 prefix 수정

- apis/exhibition.ts
Reverts YAPP-Github/21st-ALL-Rounder-Team-2-Web#68
> Revert "fix: axios url config 설정 에러 수정"

- components/pages/ArtworkCardList/ArtworkEditActionSheet.tsx
- hooks/artwork.tsx
- libs/message/message.ts
#issue
- 마지막 작품 삭제 후 NAVIGATE_TO_HOME 메시지 전송
- 작품 목록 쿼리 무효화는 스킵 (refetch할 경우 404에러)
> 마지막 작품 삭제 후 홈 화면으로 라우팅 처리

- app/exhibition/[exhibitionId]/page.tsx
- components/pages/LinkPreviewCard/LinkPreviewCard.error.tsx
- components/pages/LinkPreviewCard/LinkPreviewCard.skeleton.tsx
- components/pages/LinkPreviewCard/LinkPreviewCard.stories.tsx
- components/pages/LinkPreviewCard/LinkPreviewCard.styles.tsx
- components/pages/LinkPreviewCard/LinkPreviewCard.tsx
- components/pages/LinkPreviewCard/index.ts
- components/ui/ErrorBoundary/ErrorBoundary.tsx
#issue
- ErrorBoundary 컴포넌트 추가
- 링크 미리보기 요청 에러 처리
- 유효하지 않은 url을 등록했거나 잘못된 요청이 가는 경우 발생 
- OPEN_NEW_WINDOW 메시지는 정상적으로 전송되도록 한다
> ErrorBoundary 컴포넌트 추가, 링크 미리보기 요청 에러 처리

- components/pages/LinkPreviewCard/index.ts
> fix: client component re-export 오류 수정

- app/home/layout.tsx
- app/home/page.tsx
#issue
- ExhibitionCardList를 제외하고 layout 파일로 분리
- searchParams가 변경될 때마다 CategoryList.server 컴포넌트가 리렌더링되는 현상 개선
> home layout 분리

- components/pages/EditBottomSheet/EditBottomSheet/EditBottomSheet.tsx
#issue
- maxLength 추가하여 입력 길이 제한
- 태그 배열 length 체크하여 입력 개수 제한
- trim 적용하여 앞뒤 공백 제거
> 편집 바텀시트 validation 추가

- app/layout.tsx
> 다이나믹 서브셋 font 적용

- app/exhibition/[exhibitionId]/page.module.css
- app/exhibition/[exhibitionId]/page.tsx
- components/pages/ArtworkCardList/ArtworkCardList.server.tsx
- components/pages/ArtworkCardList/ArtworkCount.styles.tsx
- components/pages/ArtworkCardList/ArtworkCount.tsx
- hooks/artwork.server.tsx
> 작품 개수 카운트 ui 추가

- apis/exhibition.ts
- app/exhibition/[exhibitionId]/page.stories.tsx
- app/exhibition/[exhibitionId]/page.tsx
- components/pages/LinkPreviewCard/LinkPreviewCard.server.tsx
- components/pages/LinkPreviewCard/index.ts
- hooks/exhibition.server.tsx
- hooks/exhibition.tsx
#issue
- 프록시 서버 오류로 인해 next 서버 단에서 처리
- 클라이언트 단에서 리페칭되면 cors 에러가 발생하기 때문에 staleTime을 Infinity로 지정하여 리페칭 방지
> cors 우회를 위해 open graph 요청 방식 변경

- styles/globals.tsx
#issue
- user-select 속성을 none으로 지정
> feat: 텍스트 long press시 드래그되는 현상 방지

- app/calendar/components/ExhibitSelectModal/ExhibitSelectModal.styles.tsx
- app/calendar/components/ExhibitSelectModal/ExhibitSelectModal.tsx
- app/exhibition/[exhibitionId]/components/ArtworkDeleteAlertModal/ArtworkDeleteAlertModal.styles.tsx
- app/exhibition/[exhibitionId]/components/ArtworkDeleteAlertModal/ArtworkDeleteAlertModal.tsx
- app/exhibition/[exhibitionId]/components/ImageUploadSelectModal/ImageUploadSelectModal.styles.tsx
- app/exhibition/[exhibitionId]/components/ImageUploadSelectModal/ImageUploadSelectModal.tsx
- components/Modal/Modal.stories.tsx
- components/Modal/Modal.styles.tsx
- components/Modal/Modal.tsx
#issue
- 모달에서 공통적으로 사용되는 Portal, Dimmed의 위치를 Modal로 변경한다
- string으로 제한적이던 headline prop 대신 서브 컴포넌트를 추가한다
> Portal, Dimmed 컴포넌트 위치 변경 및 Modal 서브 컴포넌트 추가

- app/calendar/components/Calendar/Calendar.styles.tsx
- app/calendar/components/Calendar/Calendar.tsx
- components/Picker/DatePicker/DatePicker.styles.tsx
- components/Picker/DatePicker/DatePicker.tsx
#issue
- disabled date color에 opacity 적용
- DatePicker 커스텀 디자인 적용
> disabled date color, DatePicker 스타일 변경

- .github/workflows/ci-cd.yml
- .storybook/main.js
> storybook env 제거 및 배포 워크플로우 활성화

- app/calendar/page.tsx
- utils/datetime.ts
#issue
- getDateByYearAndMonth util 오류 수정
- 달마다 일수가 다르므로 month를 변경하기 이전에 1일로 초기화해줘야 함
> date 관련 오류 수정

- styles/globals.tsx
> style: tab-highlight-color 제거

- app/calendar/page.styles.tsx
- app/exhibition/[exhibitionId]/[artworkId]/page.styles.tsx
- app/exhibition/[exhibitionId]/[artworkId]/page.tsx
- app/home/components/ExhibitionCardList/ExhibitionCardList.styles.tsx
- components/Icon/svg/x-circle.svg
- components/Tag/Tag/Tag.styles.tsx
#issue
- padding, margin, gap 값 조정
- 아이콘 크기 조정
> space 및 아이콘 크기 조정

- hooks/artwork.tsx
> 작품 정보 수정사항이 작품 목록에 반영되지 않는 오류 해결

- app/exhibition/[exhibitionId]/components/ExhibitInformationHeader/ExhibitInformationHeader.tsx
- app/exhibition/[exhibitionId]/components/ImageUploadSelectModal/ImageUploadSelectModal.tsx
- hooks/artwork.tsx
- libs/message/message.ts
> 작품 등록 개수 제한

- app/exhibition/[exhibitionId]/[artworkId]/page.tsx
- app/exhibition/[exhibitionId]/components/ArtworkCard/ArtworkCard.tsx
- app/exhibition/[exhibitionId]/components/ExhibitInformationHeader/ExhibitInformationHeader.tsx
- app/home/components/ExhibitionCard/ExhibitionCard.tsx
- app/home/components/MainExhibitionCard/MainExhibitionCard.tsx
- components/Image/Image.styles.tsx
- components/Image/Image.tsx
- components/Skeleton/Skeleton.stories.tsx
- components/Skeleton/Skeleton.styles.tsx
- components/Skeleton/Skeleton.tsx
- styles/keyframes.css
#issue
- 스켈레톤 컴포넌트 개발
- blurDataUrl을 loadingFallback으로 대체
- 이미지 로딩 후 fade-in 효과 적용
> 이미지 로딩 스켈레톤 및 fade-in 효과 적용

- app/exhibition/[exhibitionId]/components/ArtworkCardList/ArtworkCount.styles.tsx
- app/exhibition/[exhibitionId]/components/ExhibitInformationHeader/ExhibitInformationHeader.styles.tsx
- app/home/components/Category/Category.styles.tsx
- components/ActionSheet/ActionSheet.styles.tsx
> 카테고리 transition 적용 및 letter-spacing 제거

- __generate__/user/api.ts
- apis/user.ts
- app/calendar/components/Calendar/Calendar.tsx
- components/Picker/DatePicker/DatePicker.tsx
- hooks/user.tsx
> datepicker 최소 날짜 범위를 유저 가입일로 지정

- app/exhibition/[exhibitionId]/[artworkId]/page.styles.tsx
- app/exhibition/[exhibitionId]/[artworkId]/page.tsx
> style: gradient background 추가

- app/exhibition/[exhibitionId]/[artworkId]/page.tsx
> fix: router push 대신 replace 사용
